<?php

return [

  //arabic for only here vp project
  'Dashboard' =>'Dashboard',
  'Company' =>'Company',
  'Subscription' =>'Subscription',
  'Transaction' =>'Transaction',
  'Notification' =>'Notification',
  'Add_Settings' =>'Settings',
  'Employee' =>'Employee',
  'Reception' =>'Reception',
  'App_Settings' =>'App Settings',
  'Visitor' =>'Visitor',
  'File_Changes' =>'File Changes',
  'Profile' =>'Profile',
  'Logout' =>'Logout',
  'Total_Company' =>'Total Company',
  'Active_Company' =>'Active Company',
  'Total_Transaction' =>'Total Transaction',
  'Expired_Company' =>'Expired Company',
  'Total_company_added_monthly' =>'Total company added monthly',
  'Tthis_month' =>'this month',
  'this_monthlymonth' =>'Total transaction done monthly',
  'total_companyymonth' =>'Out of total company.',
  'Expired' =>'Expired',
  'Add' =>'Add',
  'Add-search' =>'Search Here....',
  'No_Data_Found' =>'No Data Found..',
  'Displaying' =>'Displaying',
  'of' =>'of',
  'Records' =>'Records',
  'Active' =>'Active',
  'Inactive' =>'Inactive',
  'Monthly_Revenue' =>'Monthly Revenue',
  'Show_monthly_revenue' =>'Show monthly revenue',
  'Revenue-sa' =>'Revenue',
  'Recent_Company-sa' =>'Recent Company',
  'Total_Employee' =>'Total Employee',
  'Active_Employee' =>'Active Employee',
  'Total_Reception' =>'Total Reception',
  'Subscription_Expiry' =>'Subscription Expiry',
  'Total_employee_added' =>'Total employee added',
  'Total_receptionof_added' =>'Out of total employees.',
  'Visitors' =>'Visitors',
  'Show_monthly_visitors' =>'Show monthly visitors',
  'Today_Visitors' =>'Today Visitors',
  'To_whom_is_visiting' =>'To whom is visiting',
  'Company_List' =>'Company List ',
  'Add_New_Company' =>'Add New Company',
  'Update_Company' =>'Update Company',
  'Company_Name' =>'Company Name',
  'Company_Namerequired' =>'Company name is required',
  'EmailEmail' =>'Email',
  'Email-cusis' =>'Email is required',
  'Password' =>'Password',
  'Password_is_required' =>'Password is required',
  'Confirm_Password' =>'Confirm Password',
  'Confirm_requiredPassword' =>'Confirm password is required',
  'Description' =>'Description',
  'Description_required' =>'Description is required',
  'Enter_Address_Number' =>'Address',
  'Address_is_required' =>'Address is required',
  'No_Employee' =>'No.Of Employee',
  'App_Background' =>'App Background',
  'App_Background_required' =>'App Background Colour is required',
  'AppText_Colour' =>'App Text Colour',
  'AppText_ColourApp' =>'App Text Colour is required',
  'STATUS' =>'Status',
  'Company_URL' =>'Company URL',
  'Company_s_required' =>'Company URL is required',
  'Logo' =>'Logo',
  'Crop_Image' =>'Crop Image',
  'Crop_employeeImage' =>'Number of employee is required',
  'Delete' =>'Delete',
  'Close' =>'Close',
  'Crop' =>'Crop',
  'Credit_Title' =>'Title',
  'Expiry_Date' =>'Expiry Date',
  'AAction' =>'Action',
  'Price_SubscriptionD' =>'Subscription List',
  'Price' =>'Price',
  'Cancel' =>'Cancel',
  'Price_Duration' =>'Duration',
  'Update_Subscription' =>'Update Subscription',
  'AddNew_Subscription' =>'Add New Subscription',
  'Update' =>'Update',
  'Submit' =>'Submit',
  'Transaction_List' =>'Transaction List',
  'Select_Company' =>'Select Company',
  'Select_Subscription' =>'Select Subscription',
  'Search_Subscription' =>'Search Price....',
  'Validity' =>'Validity',
  'Update_Transaction' =>'Update Transaction',
  'Add_New_Transaction' =>'Add New Transaction',
  'Subscription_Type' =>'Subscription Type',
  'Purchase_Date' =>'Purchase Date',
  'Send_to' =>'Send to',
  'requiredSend_to' =>'Company is required.',
  'Title_is_required' =>'Title is required.',
  'Send_All_Company' =>'All Company',
  'Message_Company' =>'Message',
  'Message_is_required' =>'Message is required.',
  'Send_Notification' =>'Send Notification',
  'NotificationListReceiver' =>'Receiver',
  'NotificationList' =>'Notification List',

  'Dates' =>'Date',
  'View_Dates' =>'View',
  'Received-sa' =>'Received',
  'Sentived-sa' =>'Sent',
  'Notification_Details' =>'Notification Details',
  'First_Name' =>'First Name',
  'Last_Name' =>'Last Name',
  'Last_name_is_required' =>'Last name is required',
  'Designation' =>'Designation',
  'Designation_is_required' =>'Designation is required',
  'DesignatDepartment' =>'Department',
  'DesignatDepartmentrequired' =>'Department is required',
  'Office_Number' =>'Office Number',
  'Office_numb_required' =>'Office number is required',
  'Mobile_Number' =>'Mobile Number',
  'Mobile_Numberrequired' =>'Mobile no is required',
  'Profile_Picture' =>'Profile Picture',
  'Employee_List' =>'Employee List',
  'ImportedEmployee_List' =>'Excel Data Imported successfully.',
  'Select_File_for_Upload' =>'Select File for Upload',
  'Uploadfor_Upload' =>'Upload',
  'UploadforFormat_Upload' =>'Download XSLX Format To Upload',
  'Please_to_upload' =>'Please select file to upload',
  'Please_tofiles_upload' =>'You can upload only .xlsx files.',
  'Nameiles' =>'Name',
  'Update_Reminder' =>'Update Reminder',
  'Edit_Reminder' =>'Edit Reminder',
  'User_Profile' =>'User Profile',
  'Edit_User' =>'Edit User',
  'Email_Address' =>'Email Address',
  'Change_Password' =>'Change Password',
  'Changerequired_Password' =>'Current password is required.',
  'New_password_i_required' =>'New password is required',
  'New_Password' =>'New Password',
  'New_Passwordrequired' =>'Confirm password is required.',
  'Change' =>'Change',
  'Remove' =>'Remove',
  'Subscription_Name' =>'Subscription Name',
  'Visitor_List' =>'Visitor List',
  'Select_Employee' =>'Select Employee',
  'Select_Department' =>'Select Department',
  'Signature' =>'Signature',
  'Sign_In' =>'Sign In',
  'Sign_Out' =>'Sign Out',
  'Mobile_No' =>'Mobile No.',
  'Email_ID' =>'Email ID',
  'Gender' =>'Gender',
  'Created-Date' =>'Created Date',
  'Price_is_required' =>'Price is required',
  'Subscription_Namename' =>'Subscription Namename',
  'Appointment_Details' =>'Appointment Details',
  'response_Details' =>'Your response is saved successfully!',
  'response_Detailssubmitted' =>'Your response is already submitted!',
  'first_name_required-is' =>'First name is required',
  'Reception_List' =>'Reception List',
  'Reschedule_Appointment' =>'Reschedule Appointment',
  'Visiting_date_is_required' =>'Visiting date is required.',
  'VisiTime' =>'Time',
  'Visiting_time_is_required' =>'Visiting time is required.',
  'Visiting_time_is_requiredyou' =>'The time you have selected is before the Current Time. Please select a valid time.',
  'select-lngt' =>'Select language',
  'welcomeselect-lngt' =>'Welcome! Happy to see you! ',
  'E-Mail_Address' =>'E-Mail Address ',
  'E-Remember_Me' =>'Remember Me ',
  'Forgot_Your_Password' =>'Forgot Your Password',
  'login-Login' =>'Login',
  'Reset_Password' =>'Reset Password',
  'Reset_Passwordrest' =>'Send Password Reset Link',
  'account-anrest' =>'Already have an account?',
  'Notification '=>'Notification',
  'App_Setting'=>'App Setting',
  'Terms _Condition_e'=>'Terms & Condition (English)',
  'Terms _Condition_a'=>'Terms & Conditions (Arabic)',
  'Update'=>'Update',
  'Embed_Script'=>'Embed Script',
  'submit'=>'submit',
  'Search'=>'Search Here....',
  'Add_New_Reception'=>'Add New Reception',
  'Update_Reception'=>'Update Reception',
  'Update_Employee'=>'Update Employee',
  'Add_New_Employee'=>'تحديث الموظف'









  //arabic for only here vp project end


// invoce arabic



];
